// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package co.edu.udistrital.rrhh.web.converter;

import co.edu.udistrital.rrhh.web.converter.CargoConverter;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect CargoConverter_Roo_Configurable {
    
    declare @type: CargoConverter: @Configurable;
    
}
